# assistant_mapping.py

# Map all possible technical names to a single display name
TECHNICAL_TO_DISPLAY = {
    "qodo": "Qodo",
    "pycharm": "AI Assistant in PyCharm",
    "cursor": "Cursor",
    "aider": "Aider",
    "amazonq": "Amazon Q",
    "jetbrain_junie": "JetBrains Junie",
    "jetbrains_junie": "JetBrains Junie",
    "zed": "Zed Editor",
    "zededitor": "Zed Editor",
    "sourcegraph": "Sourcegraph",
    "github_copilot": "GitHub Copilot",
    "codex_edu": "Codex in ChatGPT Edu",
    "codexedu": "Codex in ChatGPT Edu",
    "codex": "Codex",
    "cline": "Cline",
    "trae": "Trae",
    "windsurf": "Windsurf",
    "firebase": "Firebase",
    "replit": "Replit",
    "tabnine": "Tabnine",
    "tabbyml": "TabbyML",
}

# Assign a unique color to each display name
DISPLAY_TO_COLOR = {
    "Qodo": "#1f77b4",
    "AI Assistant in PyCharm": "#ff7f0e",
    "Cursor": "#2ca02c",
    "Aider": "#d62728",
    "Amazon Q": "#9467bd",
    "JetBrains Junie": "#8c564b",
    "Zed Editor": "#e377c2",
    "Sourcegraph": "#7f7f7f",
    "GitHub Copilot": "#bcbd22",
    "Codex in ChatGPT Edu": "#17becf",
    "Codex": "#aec7e8",
    "Cline": "#ffbb78",
    "Trae": "#98df8a",
    "Windsurf": "#ff9896",
    "Firebase": "#c5b0d5",
    "Replit": "#c49c94",
    "Tabnine": "#f7b6d2",
    "TabbyML": "#dbdb8d",
}

GENERAL_LLM_TECHNICAL_TO_DISPLAY = {
    "nvidia_llama3_1": "NVIDIA Llama 3.1",
    "nvidia_llama3_3": "NVIDIA Llama 3.3",
    "deepseek_v3": "DeepSeek V3",
    "deepseek_v3_1": "DeepSeek V3.1",
    "deepseek_v3_2": "DeepSeek V3.2",
    "nous_hermes3": "Nous Hermes 3",
    "gemini2_5": "Gemini 2.5",
    "claude3_5sonnet": "Claude 3.5 Sonnet",
    "claude4_5sonnet": "Claude 4.5 Sonnet",
    "meta_llama3": "Meta Llama 3",
    "meta_llama4": "Meta Llama 4",
    "thudm_glm4_1": "THUDM GLM-4.1",
    "nova1": "Amazon Nova v1 Lite",
    "nova2": "Amazon Nova v2 Lite",
    "gpt4": "GPT-4",
    "gpt5": "GPT-5",
    "gpt5_1": "GPT-5.1",
    "qwen2_5": "Qwen 2.5 Coder",
    "qwen3": "Qwen 3 Coder",
    "grok2": "Grok 2",
    "grok3": "Grok 3",
    "grok4": "Grok 4",
    "phi4": "Microsoft Phi 4",
    "cohere_commandr": "Cohere Command-R",
    "perplexity_sonar": "Perplexity Sonar",
    "a21_jamba": "A21 Jamba",
    "mythomax": "MythoMax"
} 

GENERAL_LLM_OPENROUTER_CODE = {
    "nvidia_llama3_1": "nvidia/llama-3.1-nemotron-70b-instruct", 
    "nvidia_llama3_3": "nvidia/llama-3.3-nemotron-super-49b-v1.5", 
    "deepseek_v3": "deepseek/deepseek-chat",
    "deepseek_v3_1": "deepseek/deepseek-chat-v3.1",
    "deepseek_v3_2": "deepseek/deepseek-v3.2",
    "nous_hermes3": "nousresearch/hermes-3-llama-3.1-70b",
    "gemini2_5": "google/gemini-2.5-pro",
    "claude3_5sonnet": "anthropic/claude-3.5-sonnet",
    "claude4_5sonnet": "anthropic/claude-sonnet-4",
    "meta_llama3": "meta-llama/llama-3-70b-instruct",
    "meta_llama4": "meta-llama/llama-4-maverick",
    "thudm_glm4.1": "thudm/glm-4.1v-9b-thinking", 
    "nova1": "amazon/nova-lite-v1",
    "nova2": "amazon/nova-2-lite-v1",
    "gpt4": "openai/gpt-4",
    "gpt5": "openai/gpt-5",
    "gpt5_1": "openai/gpt-5.1",
    "qwen2_5": "qwen/qwen-2.5-coder-32b-instruct", 
    "qwen3": "qwen/qwen3-coder-plus",
    "grok3": "x-ai/grok-3",
    "grok4": "x-ai/grok-4",
    "phi4": "microsoft/phi-4",
    "cohere_commandr": "cohere/command-r-08-2024",
    "perplexity_sonar": "perplexity/sonar-pro",
    "a21_jamba": "ai21/jamba-large-1.7",
    "mythomax": "gryphe/mythomax-l2-13b",
}
